/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 20131tpmi0557
 */
public class Listar extends javax.swing.JInternalFrame {
     private Principal principal;
    /**
     * Creates new form Listar
     */
    public Listar(Principal principal) {
        initComponents();
        this.principal = principal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tela = new javax.swing.JTextArea();
        ordenarNome = new javax.swing.JButton();
        ordenarMatricula = new javax.swing.JButton();
        ordenarSalario = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        tela.setColumns(20);
        tela.setRows(5);
        jScrollPane1.setViewportView(tela);

        ordenarNome.setText("Nome");
        ordenarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarNomeActionPerformed(evt);
            }
        });

        ordenarMatricula.setText("Matricula");
        ordenarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarMatriculaActionPerformed(evt);
            }
        });

        ordenarSalario.setText("Salário");
        ordenarSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarSalarioActionPerformed(evt);
            }
        });

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        jLabel1.setText("Ordenar por:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(limpar)
                                .addGap(59, 59, 59)
                                .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(ordenarNome)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ordenarMatricula))
                                .addGap(35, 35, 35)
                                .addComponent(ordenarSalario)))
                        .addGap(0, 76, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ordenarMatricula)
                    .addComponent(ordenarSalario)
                    .addComponent(ordenarNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sair)
                    .addComponent(limpar))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ordenarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarNomeActionPerformed
        // TODO add your handling code here:
        BubbleSort.ordenaBolha(principal.vetorDeEmpregados,1);
        for(int i=0; i<principal.vetorDeEmpregados.size();i++){
            Empregado e =(Empregado) principal.vetorDeEmpregados.get(i);
            tela.setText(tela.getText()+ "\n" + e.getMatricula() + " " + e.getNome() + " " + e.getSalario());
        }
        
    }//GEN-LAST:event_ordenarNomeActionPerformed

    private void ordenarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarMatriculaActionPerformed
        // TODO add your handling code here:
        BubbleSort.ordenaBolha(principal.vetorDeEmpregados,0);
        for(int i=0; i<principal.vetorDeEmpregados.size();i++){
            Empregado e =(Empregado) principal.vetorDeEmpregados.get(i);
            tela.setText(tela.getText()+ "\n" + e.getMatricula() + " " + e.getNome() + " " + e.getSalario());
        }
        
    }//GEN-LAST:event_ordenarMatriculaActionPerformed

    private void ordenarSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarSalarioActionPerformed
        // TODO add your handling code here:
        BubbleSort.ordenaBolha(principal.vetorDeEmpregados,2);
        for(int i=0; i<principal.vetorDeEmpregados.size();i++){
            Empregado e =(Empregado) principal.vetorDeEmpregados.get(i);
            tela.setText(tela.getText()+ "\n" + e.getMatricula() + " " + e.getNome() + " " + e.getSalario());
        }
        
    }//GEN-LAST:event_ordenarSalarioActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        // TODO add your handling code here:
        tela.setText(" ");
    }//GEN-LAST:event_limparActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_sairActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpar;
    private javax.swing.JButton ordenarMatricula;
    private javax.swing.JButton ordenarNome;
    private javax.swing.JButton ordenarSalario;
    private javax.swing.JButton sair;
    private javax.swing.JTextArea tela;
    // End of variables declaration//GEN-END:variables
}
